# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from customwidgets import CustomQTableWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 655)
        MainWindow.setStyleSheet(
            "QPushButton {\n" "    min-width: 90px;\n" "    min-height: 30px;\n" "}"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cut_sheet_file_path_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.cut_sheet_file_path_lineedit.setEnabled(False)
        self.cut_sheet_file_path_lineedit.setObjectName("cut_sheet_file_path_lineedit")
        self.horizontalLayout.addWidget(self.cut_sheet_file_path_lineedit)
        self.cut_sheet_browse_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.cut_sheet_browse_pushbutton.setEnabled(True)
        self.cut_sheet_browse_pushbutton.setObjectName("cut_sheet_browse_pushbutton")
        self.horizontalLayout.addWidget(self.cut_sheet_browse_pushbutton)
        self.horizontalLayout.setStretch(0, 1)
        self.formLayout.setLayout(
            1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout
        )
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.total_cut_qty_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.total_cut_qty_spinbox.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.total_cut_qty_spinbox.setMinimum(1)
        self.total_cut_qty_spinbox.setMaximum(10000)
        self.total_cut_qty_spinbox.setObjectName("total_cut_qty_spinbox")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.total_cut_qty_spinbox
        )
        self.batch_size_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.batch_size_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.batch_size_spinbox.setMinimum(1)
        self.batch_size_spinbox.setMaximum(10000)
        self.batch_size_spinbox.setObjectName("batch_size_spinbox")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.batch_size_spinbox
        )
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.selected_printer_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.selected_printer_combobox.setObjectName("selected_printer_combobox")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.selected_printer_combobox
        )
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.reload_table_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reload_table_pushbutton.setEnabled(False)
        self.reload_table_pushbutton.setObjectName("reload_table_pushbutton")
        self.horizontalLayout_2.addWidget(self.reload_table_pushbutton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tablewidget = CustomQTableWidget(self.centralwidget)
        self.tablewidget.setObjectName("tablewidget")
        self.tablewidget.setColumnCount(0)
        self.tablewidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tablewidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.print_previous_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.print_previous_pushbutton.setEnabled(False)
        self.print_previous_pushbutton.setMinimumSize(QtCore.QSize(92, 32))
        self.print_previous_pushbutton.setObjectName("print_previous_pushbutton")
        self.horizontalLayout_3.addWidget(self.print_previous_pushbutton)
        self.print_single_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.print_single_pushbutton.setEnabled(False)
        self.print_single_pushbutton.setObjectName("print_single_pushbutton")
        self.horizontalLayout_3.addWidget(self.print_single_pushbutton)
        self.print_selected_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.print_selected_pushbutton.setEnabled(False)
        self.print_selected_pushbutton.setMinimumSize(QtCore.QSize(92, 32))
        self.print_selected_pushbutton.setObjectName("print_selected_pushbutton")
        self.horizontalLayout_3.addWidget(self.print_selected_pushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cut Sheet:"))
        self.cut_sheet_file_path_lineedit.setToolTip(
            _translate("MainWindow", "The current cut sheet loaded.")
        )
        self.cut_sheet_browse_pushbutton.setToolTip(
            _translate("MainWindow", "Browse for a cut sheet excel file to load.")
        )
        self.cut_sheet_browse_pushbutton.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Total Qty:"))
        self.label_3.setText(_translate("MainWindow", "Batch Size:"))
        self.total_cut_qty_spinbox.setToolTip(
            _translate("MainWindow", "The number of harnesses to be cut.")
        )
        self.batch_size_spinbox.setToolTip(
            _translate(
                "MainWindow",
                "Enter the batch size for each bundle. Used to calculate how many labels to print for each line.",
            )
        )
        self.label_4.setText(_translate("MainWindow", "Printer:"))
        self.selected_printer_combobox.setToolTip(
            _translate("MainWindow", "What Dymo printer to print to.")
        )
        self.reload_table_pushbutton.setToolTip(
            _translate(
                "MainWindow",
                "Reloads the selected cut sheet. This will repopulate the table with every wire that needs cut.",
            )
        )
        self.reload_table_pushbutton.setText(_translate("MainWindow", "Reload File"))
        self.print_previous_pushbutton.setToolTip(
            _translate(
                "MainWindow",
                "Prints a single label using the info from the last printed batch of labels.",
            )
        )
        self.print_previous_pushbutton.setText(
            _translate("MainWindow", "Print Previous")
        )
        self.print_single_pushbutton.setToolTip(
            _translate(
                "MainWindow",
                'Print one label for the selected row. This will not remove the row or change the "Bundle" column.',
            )
        )
        self.print_single_pushbutton.setText(_translate("MainWindow", "Print Single"))
        self.print_selected_pushbutton.setToolTip(
            _translate(
                "MainWindow",
                'Prints the label(s) for the selected row. The number of labels to be printed is shown in the "Bundles" column.',
            )
        )
        self.print_selected_pushbutton.setText(
            _translate("MainWindow", "Print Selected")
        )
